spring.application.name=Cementerio

# Configuración de variables de entorno (Railway / Producción)
# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:cementerio_db}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:andercOn2209}
server.port=${PORT:8081}

# Orígenes permitidos (CORS) - Por defecto localhost
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Define el dialecto de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:mi_clave_secreta_super_segura_para_el_cementerio_2026_muy_larga_para_hs256} 