spring.application.name=Cementerio

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/cementerio_db
spring.datasource.username=postgres
spring.datasource.password=andercOn2209
server.port=8081

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ¡FALTA ESTO! Define el dialecto de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=mi_clave_secreta_super_segura_para_el_cementerio_2026_muy_larga_para_hs256